name: social_sphere
description: An app to help you build your social network

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^5.1.0
  adaptive_theme: ^3.3.0
  flutter_svg: ^2.0.7
  theme_tailor_annotation: ^2.0.0
  uikit: 
    path: packages/uikit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  theme_tailor: ^2.0.0
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
